CREATE OR REPLACE VIEW VIEW_TEAMS_CHAMPIONSHIPS AS
SELECT
    t.NAME AS TEAM_NAME,
    ch.NAME AS CHAMPIONSHIP_NAME,
    ct.PLACE AS PLACE,
    ch.EVENT_DATE AS EVENT_DATE,
    ch.PRIZE AS PRIZE_MONEY
FROM TEAMS t
    JOIN CHAMPIONSHIPS_TEAMS ct ON t.ID = ct.TEAM_ID
    JOIN CHAMPIONSHIPS ch ON ct.CHAMPIONSHIP_ID = ch.ID;