CREATE OR REPLACE VIEW VIEW_CARS_ENGINES AS
SELECT
    c.NAME AS CAR_NAME,
    e.BRAND AS ENGINE_BRAND,
    e.POWER AS ENGINE_POWER,
    CONCAT(ch.HEIGHT, ' x ', ch.WIDTH, ' x ', ch.LENGTH) AS CHASSIS_TYPE
FROM CARS c
JOIN ENGINES e ON c.ENGINE_ID = e.ID
JOIN CHASSIS ch ON c.CHASSIS_ID = ch.ID;