CREATE DATABASE IF NOT EXISTS DB_ORDERS;
USE DB_ORDERS;

CREATE TABLE IF NOT EXISTS ORDERS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    ORDER_DATE DATE NOT NULL
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT UNSIGNED,
    ITEM_NAME VARCHAR(255) NOT NULL,
    QUANTITY BIGINT UNSIGNED NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL
) ENGINE=MyISAM;

ALTER TABLE ORDER_ITEMS
    ADD CONSTRAINT ORDER_ITEMS_ORDER_FK
        FOREIGN KEY(ORDER_ID)
            REFERENCES ORDERS(ID);