CREATE DATABASE IF NOT EXISTS DB_FORMULA;
USE DB_FORMULA;

CREATE TABLE IF NOT EXISTS CARS(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ENGINE_ID BIGINT UNSIGNED NOT NULL,
    CHASSIS_ID BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS PILOTS(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    SECOND_NAME VARCHAR(255) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    HEIGHT SMALLINT UNSIGNED NOT NULL,
    WEIGHT BIGINT NOT NULL,
    TEAM_ID BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS TEAMS(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    CREATE_DATE DATE NOT NULL,
    CAR_ID BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS CHASSIS(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HEIGHT DECIMAL(4,2) NOT NULL,
    WIDTH DECIMAL(4,2) NOT NULL,
    LENGTH DECIMAL(4,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS CHAMPIONSHIPS_TEAMS(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CHAMPIONSHIP_ID BIGINT UNSIGNED NOT NULL,
    TEAM_ID BIGINT UNSIGNED NOT NULL,
    PLACE SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS CHAMPIONSHIPS(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    EVENT_DATE DATE NOT NULL,
    PRIZE BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS ENGINES(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BRAND VARCHAR(255) NOT NULL,
    POWER SMALLINT UNSIGNED NOT NULL,
    CAPACITY INT UNSIGNED NOT NULL,
    CYLINDERS SMALLINT UNSIGNED NOT NULL
);

# SELECT COUNT(*) INTO @cnt FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
# WHERE REFERENCED_TABLE_SCHEMA = 'DB_FORMULA'
#   AND REFERENCED_TABLE_NAME = 'TEAMS'
#   AND CONSTRAINT_NAME = 'CHAMPIONSHIPS_TEAMS_TEAMS_FK';
#
# IF @cnt = 0
# THEN
# ALTER TABLE CHAMPIONSHIPS_TEAMS
#     ADD CONSTRAINT CHAMPIONSHIPS_TEAMS_TEAMS_FK
#     FOREIGN KEY (TEAM_ID)
#     REFERENCES TEAMS(ID);
# END IF;

# IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS
# WHERE REFERENCED_TABLE_SCHEMA = 'DB_FORMULA'
#   AND REFERENCED_TABLE_NAME = 'TEAMS'
#   AND CONSTRAINT_NAME = 'CHAMPIONSHIPS_TEAMS_TEAMS_FK')
# THEN
# ALTER TABLE CHAMPIONSHIPS_TEAMS
#     ADD CONSTRAINT CHAMPIONSHIPS_TEAMS_TEAMS_FK
#     FOREIGN KEY (TEAM_ID)
#     REFERENCES TEAMS(ID);
# END IF;

# IF NOT EXISTS (SELECT 1 FROM [INFORMATION_SCHEMA].[TABLE_CONSTRAINTS] WHERE [CONSTRAINT_TYPE] = 'PRIMARY KEY' AND [TABLE_NAME] = N'COMMENTS') BEGIN
# ALTER TABLE [dbo].[COMMENTS] ADD CONSTRAINT [PK_COMMENTS_UID] PRIMARY KEY CLUSTERED ([UID] ASC)
#     PRINT N'➕ PRIMARY KEY [PK_COMMENTS_UID] WAS CREATED';
# END;
#
# BEGIN TRAN
#
# IF NOT EXIST (
#    FROM information_schema.REFERENTIAL_CONSTRAINTS
#     WHERE CONSTRAINT_SCHEMA = 'DB_FORMULA'
#         AND TABLE_NAME = 'CHAMPIONSHIPS_TEAMS'
#         AND CONSTRAINT_NAME = 'CHAMPIONSHIPS_TEAMS_TEAMS_FK')
# ) BEGIN
#     ALTER TABLE CHAMPIONSHIPS_TEAMS
#     ADD CONSTRAINT CHAMPIONSHIPS_TEAMS_TEAMS_FK
#         FOREIGN KEY (TEAM_ID)
#             REFERENCES TEAMS(ID);
# END;
# END;
#
# BEGIN
#     SET @cnt = (SELECT COUNT(*)
#                 FROM information_schema.REFERENTIAL_CONSTRAINTS
#                 WHERE CONSTRAINT_SCHEMA = 'DB_FORMULA'
#                   AND TABLE_NAME = 'CHAMPIONSHIPS_TEAMS'
#                   AND CONSTRAINT_NAME = 'CHAMPIONSHIPS_TEAMS_TEAMS_FK');
#
#     IF @cnt = 0 THEN
#     ALTER TABLE CHAMPIONSHIPS_TEAMS
#         ADD CONSTRAINT CHAMPIONSHIPS_TEAMS_TEAMS_FK
#             FOREIGN KEY (TEAM_ID)
#                 REFERENCES TEAMS(ID);
#     END IF;
# END;

DELIMITER $$

CREATE FUNCTION CHECK_FK_EXIST(TABLE_NAME VARCHAR(100), REFERENCED_TABLE_NAME VARCHAR(100), CONSTRAINT_NAME VARCHAR(100))
    RETURNS BOOLEAN
BEGIN
    DECLARE cnt INT;
    SELECT COUNT(*)
    INTO cnt
    FROM information_schema.REFERENTIAL_CONSTRAINTS
    WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = TABLE_NAME
      AND REFERENCED_TABLE_NAME = REFERENCED_TABLE_NAME AND CONSTRAINT_NAME = CONSTRAINT_NAME;
    IF cnt > 0 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END$$
DELIMITER ;

DELIMITER //

CREATE PROCEDURE ADD_FOREIGN_KEYS_IN_NOT_EXIST()
BEGIN
    DECLARE cnt INT;
    SELECT CHECK_FK_EXIST('CHAMPIONSHIPS_TEAMS',
                'TEAMS',
                     'CHAMPIONSHIPS_TEAM_TEAMS_FK') INTO cnt;

    IF CHECK_FK_EXIST(
        'CHAMPIONSHIPS_TEAMS',
        'TEAMS',
        'CHAMPIONSHIPS_TEAM_TEAMS_FK'
        )
        THEN
        ALTER TABLE CHAMPIONSHIPS_TEAMS
            ADD CONSTRAINT CHAMPIONSHIPS_TEAMS_TEAMS_FK
                FOREIGN KEY (TEAM_ID)
                    REFERENCES TEAMS(ID);
    END IF;
END //

# ALTER TABLE CHAMPIONSHIPS_TEAMS
#     ADD CONSTRAINT CHAMPIONSHIPS_TEAMS_TEAMS_FK
#     FOREIGN KEY (TEAM_ID)
#     REFERENCES TEAMS(ID);

ALTER TABLE CHAMPIONSHIPS_TEAMS
    ADD CONSTRAINT CHAMPIONSHIPS_TEAMS_CHAMPIONSHIPS_FK
    FOREIGN KEY(CHAMPIONSHIP_ID)
    REFERENCES CHAMPIONSHIPS(ID);

ALTER TABLE PILOTS
    ADD CONSTRAINT PILOTS_TEAMS_FK
    FOREIGN KEY(TEAM_ID)
    REFERENCES TEAMS(ID);

ALTER TABLE TEAMS
    ADD CONSTRAINT TEAMS_CARS_FK
    FOREIGN KEY(CAR_ID)
    REFERENCES CARS(ID);

ALTER TABLE CARS
    ADD CONSTRAINT CARS_ENGINES_FK
    FOREIGN KEY(ENGINE_ID)
    REFERENCES ENGINES(ID);

ALTER TABLE CARS
    ADD CONSTRAINT CARS_CHASSIS_FK
    FOREIGN KEY(CHASSIS_ID)
    REFERENCES CHASSIS(ID);