CREATE DATABASE IF NOT EXISTS DB_FORMULA;
USE DB_FORMULA;

CREATE TABLE IF NOT EXISTS CARS(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ENGINE_ID BIGINT UNSIGNED NOT NULL,
    CHASSIS_ID BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS PILOTS(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    SECOND_NAME VARCHAR(255) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    HEIGHT SMALLINT UNSIGNED NOT NULL,
    WEIGHT BIGINT NOT NULL,
    TEAM_ID BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS TEAMS(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    CREATE_DATE DATE NOT NULL,
    CAR_ID BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS CHASSIS(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HEIGHT DECIMAL(4,2) NOT NULL,
    WIDTH DECIMAL(4,2) NOT NULL,
    LENGTH DECIMAL(4,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS CHAMPIONSHIPS_TEAMS(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CHAMPIONSHIP_ID BIGINT UNSIGNED NOT NULL,
    TEAM_ID BIGINT UNSIGNED NOT NULL,
    PLACE SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS CHAMPIONSHIPS(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    EVENT_DATE DATE NOT NULL,
    PRIZE BIGINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS ENGINES(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BRAND VARCHAR(255) NOT NULL,
    POWER SMALLINT UNSIGNED NOT NULL,
    CAPACITY INT UNSIGNED NOT NULL,
    CYLINDERS SMALLINT UNSIGNED NOT NULL
);

DELIMITER $$

DROP PROCEDURE IF EXISTS CHECK_FK_EXIST;
CREATE FUNCTION CHECK_FK_EXIST(TABLE_NAME VARCHAR(100), REFERENCED_TABLE_NAME VARCHAR(100), CONSTRAINT_NAME VARCHAR(100))
    RETURNS BOOLEAN
    DETERMINISTIC
    READS SQL DATA
BEGIN
    DECLARE cnt INT;
    SELECT COUNT(*)
    INTO cnt
    FROM information_schema.REFERENTIAL_CONSTRAINTS
    WHERE CONSTRAINT_SCHEMA = DATABASE() AND TABLE_NAME = TABLE_NAME
      AND REFERENCED_TABLE_NAME = REFERENCED_TABLE_NAME AND CONSTRAINT_NAME = CONSTRAINT_NAME;
    IF cnt > 0 THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END$$
DELIMITER ;

DELIMITER //

DROP PROCEDURE IF EXISTS ADD_FOREIGN_KEYS_IN_NOT_EXIST;
CREATE PROCEDURE ADD_FOREIGN_KEYS_IN_NOT_EXIST()
BEGIN
    IF NOT CHECK_FK_EXIST(
        'CHAMPIONSHIPS_TEAMS',
        'TEAMS',
        'CHAMPIONSHIPS_TEAM_TEAMS_FK'
        )
        THEN
        ALTER TABLE CHAMPIONSHIPS_TEAMS
            ADD CONSTRAINT CHAMPIONSHIPS_TEAMS_TEAMS_FK
                FOREIGN KEY (TEAM_ID)
                    REFERENCES TEAMS(ID);
    END IF;

    IF NOT CHECK_FK_EXIST(
            'CHAMPIONSHIPS_TEAMS',
            'CHAMPIONSHIPS',
            'CHAMPIONSHIPS_TEAMS_CHAMPIONSHIPS_FK'
        )
    THEN
        ALTER TABLE CHAMPIONSHIPS_TEAMS
            ADD CONSTRAINT CHAMPIONSHIPS_TEAMS_CHAMPIONSHIPS_FK
                FOREIGN KEY (TEAM_ID)
                    REFERENCES CHAMPIONSHIPS(ID);
    END IF;

    IF NOT CHECK_FK_EXIST(
            'PILOTS',
            'TEAMS',
            'PILOTS_TEAMS_FK'
        )
    THEN
        ALTER TABLE PILOTS
            ADD CONSTRAINT PILOTS_TEAMS_FK
                FOREIGN KEY(TEAM_ID)
                    REFERENCES TEAMS(ID);
    END IF;

    IF NOT CHECK_FK_EXIST(
            'TEAMS',
            'CARS',
            'TEAMS_CARS_FK'
        )
    THEN
        ALTER TABLE TEAMS
            ADD CONSTRAINT TEAMS_CARS_FK
                FOREIGN KEY(CAR_ID)
                    REFERENCES CARS(ID);
    END IF;

    IF NOT CHECK_FK_EXIST(
            'CARS',
            'ENGINES',
            'CARS_ENGINES_FK'
        )
    THEN
        ALTER TABLE CARS
            ADD CONSTRAINT CARS_ENGINES_FK
                FOREIGN KEY(ENGINE_ID)
                    REFERENCES ENGINES(ID);
    END IF;

    IF NOT CHECK_FK_EXIST(
            'CARS',
            'CHASSIS',
            'CARS_CHASSIS_FK'
        )
    THEN
        ALTER TABLE CARS
            ADD CONSTRAINT CARS_CHASSIS_FK
                FOREIGN KEY(CHASSIS_ID)
                    REFERENCES CHASSIS(ID);
    END IF;
END //

call ADD_FOREIGN_KEYS_IN_NOT_EXIST();