IF EXIST(
    SELECT COLUMN_NAME,
           CONSTRAINT_NAME,
           REFERENCED_TABLE_NAME,
           REFERENCED_COLUMN_NAME,
           REFERENCED_TABLE_SCHEMA
    FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
    WHERE REFERENCED_TABLE_SCHEMA = 'DB_FORMULA'
    AND REFERENCED_TABLE_NAME = 'TEAMS'
    AND CONSTRAINT_NAME = 'CHAMPIONSHIPS_TEAMS_TEAMS_FK'
) THEN (
    select '** It is already exist' AS '** DEBUG:';
)
END IF;
