SELECT
    c.NAME AS CAR_NAME,
    e.BRAND AS ENGINE_BRAND,
    e.POWER AS ENGINE_POWER,
    e.CAPACITY AS ENGINE_CAPACITY,
    e.CYLINDERS AS ENGINE_CYLINDERS,
    ch.HEIGHT AS CHASSIS_HEIGHT,
    ch.WIDTH AS CHASSIS_WIDTH,
    ch.LENGTH AS CHASSIS_LENGTH
FROM CARS c
    JOIN ENGINES e ON e.ID = c.ENGINE_ID
    JOIN CHASSIS ch ON ch.ID = c.CHASSIS_ID;